# Generated by Django 3.0.1 on 2020-01-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('category', models.CharField(choices=[('Fashion', 'Fashion'), ('Grocessory', 'Grocessory'), ('Electronics', 'Electronics')], max_length=30)),
            ],
        ),
    ]
