# Generated by Django 3.0.1 on 2020-01-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_item_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='pdf',
            field=models.FileField(upload_to='media/items/pdfs/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
